In [2]:
from scipy import signal
import numpy as np

# input signal
I = np.array([[4, 5, 6], [7, 8, 9]])
print('I: ', I.shape)
print(I)

# filter
F = np.array([[1], [1], [1]])
print('F: ', F.shape)
print(F)

# number columns and rows of the input
I_row_num, I_col_num = I.shape

# number of columns and rows of the filter
F_row_num, F_col_num = F.shape

#  calculate the output dimensions
output_row_num = I_row_num + F_row_num - 1
output_col_num = I_col_num + F_col_num - 1
print('output dimension:', output_row_num, output_col_num)


lib_output = signal.convolve2d(I, F, "full")
print('Result using signal processing library\n', lib_output)

I:  (2, 3)
[[4 5 6]
 [7 8 9]]
F:  (3, 1)
[[1]
 [1]
 [1]]
output dimension: 4 3
Result using signal processing library
 [[ 4  5  6]
 [11 13 15]
 [11 13 15]
 [ 7  8  9]]
